stady/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

stadyApp/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import ProductViewSet, LessonViewSet

router = routers.DefaultRouter()
router.register(r'products', ProductViewSet)
router.register(r'lessons', LessonViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

stadyApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    start_datetime = models.DateTimeField()
    cost = models.DecimalField(max_digits=10, decimal_places=2)


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, default='pending')


class Lesson(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    video_link = models.URLField()


class Group(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    min_users = models.PositiveIntegerField()
    max_users = models.PositiveIntegerField()
    users = models.ManyToManyField(User, related_name='groups')

stadyApp/views.py
# views.py

from rest_framework import viewsets
from .models import Product, Lesson
from .serializers import ProductSerializer, LessonSerializer, ProductDetailSerializer

class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

    def list(self, request, *args, **kwargs):
        serializer = ProductDetailSerializer(self.queryset, many=True)
        return Response(serializer.data)

stadyApp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

stadyApp/templates/lessons_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lessons List</title>
</head>
<body>
    <h1>Lessons for Product: {{ product.name }}</h1>
    <ul>
        {% for lesson in lessons %}
            <li>
                <strong>{{ lesson.title }}</strong>
                <p>Video Link: <a href="{{ lesson.video_link }}" target="_blank">{{ lesson.video_link }}</a></p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

stadyApp/templates/products_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Products List</title>
</head>
<body>
    <h1>Available Products</h1>
    <ul>
        {% for product in products %}
            <li>
                <strong>{{ product.name }}</strong>
                <p>Starts: {{ product.start_datetime }}</p>
                <p>Cost: ${{ product.cost }}</p>
                <p>Number of Lessons: {{ product.lesson_set.count }}</p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>